name: first_workflow
on: push
jobs:
  run-linter: 
    name: linting code
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
            node-version: 18

      - name: Install Node.js dependencies
        run: npm install --save-dev eslint prettier eslint-config-prettier eslint-plugin-prettier
        run: npm ci       #this will take of specific versions being installed as per package-lock.json, without causing any issues

      - name: run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  test:
    name: run unit tests
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 'Install Deps'
      run: npm install
    - name: 'Test'
      run: npx vitest --coverage.enabled true
    - name: 'Report Coverage'
      # Set if: always() to also generate the report if tests are failing
      # Only works if you set `reportOnFailure: true` in your vite config as specified above
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2

  build:
    name: build application
    runs-on: ubuntu-latest
    needs: [run-linter, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Application
        run: npm run build
